"""split oauth provider uniqueness by owner

Revision ID: 0057b18cf413
Revises: 6c26a71cb45b
Create Date: 2026-08-30 07:55:35.695453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0057b18cf413'
down_revision: Union[str, Sequence[str], None] = '6c26a71cb45b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_provider_account'), 'oauth_accounts', type_='unique')
    op.create_index('uq_oauth_client_provider', 'oauth_accounts', ['provider', 'provider_user_id'], unique=True, postgresql_where=sa.text('client_id IS NOT NULL'))
    op.create_index('uq_oauth_executor_provider', 'oauth_accounts', ['provider', 'provider_user_id'], unique=True, postgresql_where=sa.text('executor_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_oauth_executor_provider', table_name='oauth_accounts', postgresql_where=sa.text('executor_id IS NOT NULL'))
    op.drop_index('uq_oauth_client_provider', table_name='oauth_accounts', postgresql_where=sa.text('client_id IS NOT NULL'))
    op.create_unique_constraint(op.f('uq_provider_account'), 'oauth_accounts', ['provider', 'provider_user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
