"""make price per km a nullable field

Revision ID: 03dd8704ccbd
Revises: 0057b18cf413
Create Date: 2026-08-30 08:21:55.128703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03dd8704ccbd'
down_revision: Union[str, Sequence[str], None] = '0057b18cf413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('executors', 'price_per_km',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('executors', 'price_per_km',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
