"""add required tables to db

Revision ID: 16a808b2ece6
Revises: 
Create Date: 2026-08-27 11:22:19.427655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16a808b2ece6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('VIN_code', sa.String(length=17), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_VIN_code'), 'clients', ['VIN_code'], unique=True)
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=True)
    op.create_index(op.f('ix_clients_phone_number'), 'clients', ['phone_number'], unique=True)
    op.create_table('executors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('carrier', 'supplier', 'service', 'towtruck', name='executortypes'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('price_per_km', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('oauth_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('executor_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['executor_id'], ['executors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_provider_account')
    )
    op.create_index(op.f('ix_oauth_accounts_client_id'), 'oauth_accounts', ['client_id'], unique=False)
    op.create_index(op.f('ix_oauth_accounts_executor_id'), 'oauth_accounts', ['executor_id'], unique=False)
    op.create_index(op.f('ix_oauth_accounts_provider_user_id'), 'oauth_accounts', ['provider_user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('executor_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_jti', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['executor_id'], ['executors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_client_id'), 'refresh_tokens', ['client_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_executor_id'), 'refresh_tokens', ['executor_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    op.create_table('services',
    sa.Column('executor_id', sa.Integer(), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('unp', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('brands', sa.Enum('all', 'abarth', 'acura', 'aiways', 'alfa_romeo', 'alpine', 'aston_martin', 'audi', 'baic', 'bentley', 'bestune', 'bmw', 'byd', 'cadillac', 'changan', 'chery', 'chevrolet', 'chrysler', 'citroen', 'cupra', 'dacia', 'daewoo', 'daihatsu', 'dodge', 'dongfeng', 'ds', 'exeed', 'ferrari', 'fiat', 'fisker', 'ford', 'gac', 'geely', 'genesis', 'gmc', 'great_wall', 'haval', 'honda', 'hongqi', 'hummer', 'hyundai', 'infiniti', 'isuzu', 'iveco', 'jac', 'jaguar', 'jeep', 'jetour', 'kia', 'koenigsegg', 'lada', 'lamborghini', 'lancia', 'land_rover', 'leapmotor', 'lexus', 'lifan', 'lincoln', 'lotus', 'lucid', 'lynk_and_co', 'maserati', 'maybach', 'mazda', 'mclaren', 'mercedes', 'mg', 'mini', 'mitsubishi', 'nio', 'nissan', 'opel', 'pagani', 'peugeot', 'polestar', 'porsche', 'ram', 'renault', 'rivian', 'rolls_royce', 'rover', 'saab', 'seat', 'skoda', 'smart', 'ssangyong', 'subaru', 'suzuki', 'tata', 'tesla', 'toyota', 'vinfast', 'volkswagen', 'volvo', 'voyah', 'xpeng', 'zeekr', name='carbrands'), nullable=False),
    sa.ForeignKeyConstraint(['executor_id'], ['executors.id'], ),
    sa.PrimaryKeyConstraint('executor_id'),
    sa.UniqueConstraint('unp')
    )
    op.create_table('suppliers',
    sa.Column('executor_id', sa.Integer(), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('unp', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['executor_id'], ['executors.id'], ),
    sa.PrimaryKeyConstraint('executor_id'),
    sa.UniqueConstraint('unp')
    )
    op.create_table('tow_trucks',
    sa.Column('executor_id', sa.Integer(), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('unp', sa.String(length=50), nullable=False),
    sa.Column('is_available_for_work', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['executor_id'], ['executors.id'], ),
    sa.PrimaryKeyConstraint('executor_id'),
    sa.UniqueConstraint('unp')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('executor_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('truck', 'special_equipment', 'towtruck', name='vehicletypes'), nullable=False),
    sa.Column('brand', sa.Enum('all', 'abarth', 'acura', 'aiways', 'alfa_romeo', 'alpine', 'aston_martin', 'audi', 'baic', 'bentley', 'bestune', 'bmw', 'byd', 'cadillac', 'changan', 'chery', 'chevrolet', 'chrysler', 'citroen', 'cupra', 'dacia', 'daewoo', 'daihatsu', 'dodge', 'dongfeng', 'ds', 'exeed', 'ferrari', 'fiat', 'fisker', 'ford', 'gac', 'geely', 'genesis', 'gmc', 'great_wall', 'haval', 'honda', 'hongqi', 'hummer', 'hyundai', 'infiniti', 'isuzu', 'iveco', 'jac', 'jaguar', 'jeep', 'jetour', 'kia', 'koenigsegg', 'lada', 'lamborghini', 'lancia', 'land_rover', 'leapmotor', 'lexus', 'lifan', 'lincoln', 'lotus', 'lucid', 'lynk_and_co', 'maserati', 'maybach', 'mazda', 'mclaren', 'mercedes', 'mg', 'mini', 'mitsubishi', 'nio', 'nissan', 'opel', 'pagani', 'peugeot', 'polestar', 'porsche', 'ram', 'renault', 'rivian', 'rolls_royce', 'rover', 'saab', 'seat', 'skoda', 'smart', 'ssangyong', 'subaru', 'suzuki', 'tata', 'tesla', 'toyota', 'vinfast', 'volkswagen', 'volvo', 'voyah', 'xpeng', 'zeekr', name='carbrands'), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('cargo_capacity', sa.Integer(), nullable=False),
    sa.Column('volume_capacity', sa.Integer(), nullable=True),
    sa.Column('car_type', sa.Enum('sedan', 'hatchback', 'coupe', 'convertible', 'suv', 'crossover', 'minivan', 'van', 'pickup', name='cartypes'), nullable=True),
    sa.Column('license_plate', sa.String(length=10), nullable=False),
    sa.Column('manufacture_year', sa.SmallInteger(), nullable=False),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('VIN', sa.String(length=17), nullable=True),
    sa.CheckConstraint('manufacture_year >= 1960 AND manufacture_year <= 2026', name='ck_vehicle_manufacture_year'),
    sa.ForeignKeyConstraint(['executor_id'], ['executors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('VIN'),
    sa.UniqueConstraint('license_plate')
    )
    op.create_index(op.f('ix_vehicles_executor_id'), 'vehicles', ['executor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_executor_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_table('tow_trucks')
    op.drop_table('suppliers')
    op.drop_table('services')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_executor_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_client_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_oauth_accounts_provider_user_id'), table_name='oauth_accounts')
    op.drop_index(op.f('ix_oauth_accounts_executor_id'), table_name='oauth_accounts')
    op.drop_index(op.f('ix_oauth_accounts_client_id'), table_name='oauth_accounts')
    op.drop_table('oauth_accounts')
    op.drop_table('executors')
    op.drop_index(op.f('ix_clients_phone_number'), table_name='clients')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_index(op.f('ix_clients_VIN_code'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
