"""chat schemas

Revision ID: 266702b1b01c
Revises: 96e1b59e383f
Create Date: 2026-10-03 09:49:02.175050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '266702b1b01c'
down_revision: Union[str, Sequence[str], None] = '96e1b59e383f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('executor_id', sa.Integer(), nullable=False),
    sa.Column('client_last_read_id', sa.Integer(), server_default='0', nullable=False),
    sa.Column('executor_last_read_id', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['executor_id'], ['executors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['cargo_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'executor_id', name='uq_conversations_order_executor')
    )
    op.create_index('ix_conversations_client_last_message', 'conversations', ['client_id', 'last_message_at'], unique=False)
    op.create_index('ix_conversations_executor_last_message', 'conversations', ['executor_id', 'last_message_at'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('author_type', sa.Enum('client', 'executor', 'system', name='offer_author_type'), nullable=False),
    sa.Column('author_client_id', sa.Integer(), nullable=True),
    sa.Column('author_executor_id', sa.Integer(), nullable=True),
    sa.Column('parent_offer_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='RUB', nullable=False),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', 'countered', 'withdrawn', 'expired', name='offer_status'), server_default='pending', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(author_type = 'client'   AND author_client_id IS NOT NULL AND author_executor_id IS NULL) OR (author_type = 'executor' AND author_executor_id IS NOT NULL AND author_client_id IS NULL)", name='ck_offers_author'),
    sa.ForeignKeyConstraint(['author_client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['author_executor_id'], ['executors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_offer_id'], ['offers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_offers_conversation', 'offers', ['conversation_id'], unique=False)
    op.create_index('ix_offers_pending_expires', 'offers', ['expires_at'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_index('uq_one_pending_offer', 'offers', ['conversation_id'], unique=True, postgresql_where=sa.text("status = 'pending'"))
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_type', sa.Enum('client', 'executor', 'system', name='message_sender_type'), server_default='system', nullable=False),
    sa.Column('sender_client_id', sa.Integer(), nullable=True),
    sa.Column('sender_executor_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('text', 'media', 'offer', 'system', name='message_type'), server_default='text', nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(sender_type = 'client'   AND sender_client_id IS NOT NULL AND sender_executor_id IS NULL) OR (sender_type = 'executor' AND sender_executor_id IS NOT NULL AND sender_client_id IS NULL) OR (sender_type = 'system'   AND sender_client_id IS NULL AND sender_executor_id IS NULL)", name='ck_messages_sender'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_executor_id'], ['executors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_conv_id', 'messages', ['conversation_id', 'id'], unique=False)
    op.create_index('uq_messages_idempotency', 'messages', ['conversation_id', 'idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uploader_type', sa.Enum('client', 'executor', 'system', name='attachment_uploader_type'), nullable=False),
    sa.Column('uploader_client_id', sa.Integer(), nullable=True),
    sa.Column('uploader_executor_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(uploader_type = 'client'   AND uploader_client_id IS NOT NULL AND uploader_executor_id IS NULL) OR (uploader_type = 'executor' AND uploader_executor_id IS NOT NULL AND uploader_client_id IS NULL)", name='ck_attachments_uploader'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploader_client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploader_executor_id'], ['executors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_attachments_message_id'), 'attachments', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attachments_message_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index('uq_messages_idempotency', table_name='messages', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_index('ix_messages_conv_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index('uq_one_pending_offer', table_name='offers', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index('ix_offers_pending_expires', table_name='offers', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index('ix_offers_conversation', table_name='offers')
    op.drop_table('offers')
    op.drop_index('ix_conversations_executor_last_message', table_name='conversations')
    op.drop_index('ix_conversations_client_last_message', table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
