"""request schema

Revision ID: 3ccdc574e767
Revises: c5741b4073d6
Create Date: 2026-09-22 14:23:51.579966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = '3ccdc574e767'
down_revision: Union[str, Sequence[str], None] = 'c5741b4073d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # spatial_index=True: GiST-индекс idx_routes_path создаёт сам GeoAlchemy2
    # (через событие after_parent_attach на колонке Geometry). Отдельный
    # op.create_index здесь падал с DuplicateTableError, потому что индекс
    # с тем же именем уже создан во время этой же миграции.
    op.add_column('routes', sa.Column('path', Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.add_column('routes', sa.Column('distance_km', sa.Float(), nullable=True))
    op.add_column('routes', sa.Column('duration_min', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Индекс idx_routes_path удаляется вместе с колонкой path.
    op.drop_column('routes', 'duration_min')
    op.drop_column('routes', 'distance_km')
    op.drop_column('routes', 'path')
    # ### end Alembic commands ###
