"""add imageurl to accounts and price_per_km to vehicles

Revision ID: 48323bd411e0
Revises: de45835f6ccf
Create Date: 2026-09-03 14:53:31.326409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48323bd411e0'
down_revision: Union[str, Sequence[str], None] = 'de45835f6ccf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.add_column('executors', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.drop_column('executors', 'price_per_km')
    op.add_column('vehicles', sa.Column('price_per_km', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'price_per_km')
    op.add_column('executors', sa.Column('price_per_km', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('executors', 'image_url')
    op.drop_column('clients', 'image_url')
    # ### end Alembic commands ###
