"""make token owner columns nullable

Revision ID: 6c26a71cb45b
Revises: f7949d295281
Create Date: 2026-08-30 07:49:59.699629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c26a71cb45b'
down_revision: Union[str, Sequence[str], None] = 'f7949d295281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oauth_accounts', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('oauth_accounts', 'executor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_check_constraint('ck_oauth_accounts_one_owner', 'oauth_accounts', '(client_id IS NULL) <> (executor_id IS NULL)')
    op.alter_column('refresh_tokens', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('refresh_tokens', 'executor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_check_constraint('ck_refresh_tokens_one_owner', 'refresh_tokens', '(client_id IS NULL) <> (executor_id IS NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_refresh_tokens_one_owner', 'refresh_tokens', type_='check')
    op.alter_column('refresh_tokens', 'executor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('refresh_tokens', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('ck_oauth_accounts_one_owner', 'oauth_accounts', type_='check')
    op.alter_column('oauth_accounts', 'executor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('oauth_accounts', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
