"""cargo request schema

Revision ID: 96e1b59e383f
Revises: 3ccdc574e767
Create Date: 2026-09-22 14:28:02.534001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = '96e1b59e383f'
down_revision: Union[str, Sequence[str], None] = '3ccdc574e767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargo_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('origin_address', sa.String(length=500), nullable=False),
    sa.Column('origin_location', Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('destination_address', sa.String(length=500), nullable=False),
    sa.Column('destination_location', Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('cargo_type', sa.String(length=100), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('volume_m3', sa.Float(), nullable=True),
    sa.Column('vehicle_type', sa.String(length=100), nullable=True),
    sa.Column('loading_date', sa.Date(), nullable=False),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('new', 'in_progress', 'completed', 'cancelled', name='cargo_request_status'), server_default='new', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # GiST-индексы idx_cargo_requests_origin_location / idx_cargo_requests_destination_location
    # создаёт сам GeoAlchemy2 (Geometry(spatial_index=True)) во время create_table,
    # поэтому отдельные op.create_index здесь не нужны — иначе DuplicateTableError.
    op.create_index('ix_cargo_requests_client_created', 'cargo_requests', ['client_id', 'created_at'], unique=False, postgresql_where=sa.text('NOT is_deleted'))
    op.create_index('ix_cargo_requests_feed', 'cargo_requests', ['status', 'created_at'], unique=False, postgresql_where=sa.text('NOT is_deleted'))
    op.create_index('ix_cargo_requests_loading_date', 'cargo_requests', ['loading_date'], unique=False, postgresql_where=sa.text("NOT is_deleted AND status = 'new'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cargo_requests_loading_date', table_name='cargo_requests', postgresql_where=sa.text("NOT is_deleted AND status = 'new'"))
    op.drop_index('ix_cargo_requests_feed', table_name='cargo_requests', postgresql_where=sa.text('NOT is_deleted'))
    op.drop_index('ix_cargo_requests_client_created', table_name='cargo_requests', postgresql_where=sa.text('NOT is_deleted'))
    op.drop_table('cargo_requests')
    # Native enum-тип не удаляется вместе с таблицей: без этого повторный
    # upgrade падает с "type cargo_request_status already exists".
    op.execute('DROP TYPE IF EXISTS cargo_request_status')
    # ### end Alembic commands ###
