"""__tmp_sync_check__

Revision ID: ad310a8f27e5
Revises: 0a81fa2b8b3d
Create Date: 2026-09-03 15:09:43.825016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad310a8f27e5'
down_revision: Union[str, Sequence[str], None] = '0a81fa2b8b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
