"""membership schemas

Revision ID: ae6d0a4e1acc
Revises: 530176d10608
Create Date: 2026-09-05 09:01:40.583439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae6d0a4e1acc'
down_revision: Union[str, Sequence[str], None] = '530176d10608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_popular', sa.Boolean(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('is_trial', sa.Boolean(), nullable=False),
    sa.CheckConstraint('NOT (is_trial IS TRUE AND is_available IS TRUE)', name='ck_membership_trial_not_available'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('membership_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_features_membership_id'), 'features', ['membership_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('executor_id', sa.Integer(), nullable=True),
    sa.Column('membership_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'CANCELLED', 'SUSPENDED', name='subscriptionstatus'), nullable=False),
    sa.Column('source', sa.Enum('TRIAL_GRANT', 'PURCHASE', name='subscriptionsource'), nullable=False),
    sa.Column('auto_renewal', sa.Boolean(), nullable=False),
    sa.Column('subscription_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subscription_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspended_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(client_id IS NOT NULL AND executor_id IS NULL) OR (client_id IS NULL AND executor_id IS NOT NULL)', name='ck_subscription_owner_xor'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['executor_id'], ['executors.id'], ),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_client_id'), 'subscriptions', ['client_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_executor_id'), 'subscriptions', ['executor_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_membership_id'), 'subscriptions', ['membership_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('request_id', sa.String(length=255), nullable=False),
    sa.Column('bepaid_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', name='uq_transactions_request_id')
    )
    op.create_index(op.f('ix_transactions_subscription_id'), 'transactions', ['subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_subscription_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_subscriptions_membership_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_executor_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_client_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_features_membership_id'), table_name='features')
    op.drop_table('features')
    op.drop_table('memberships')
    # ### end Alembic commands ###
