"""post schema

Revision ID: c5741b4073d6
Revises: 1c00d66816ff
Create Date: 2026-09-22 13:55:55.344120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5741b4073d6'
down_revision: Union[str, Sequence[str], None] = '1c00d66816ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('request_text', sa.Text(), nullable=False),
    sa.Column('creator_type', sa.Enum('client', 'executor', name='post_creator_type'), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('executor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("(creator_type = 'client' AND client_id IS NOT NULL AND executor_id IS NULL) OR (creator_type = 'executor' AND executor_id IS NOT NULL AND client_id IS NULL)", name='ck_posts_single_creator'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['executor_id'], ['executors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        'ix_posts_feed',
        'posts',
        ['created_at'],
        unique=False,
        postgresql_where=sa.text('NOT is_deleted'),
    )
    op.create_index(
        'ix_posts_client_created',
        'posts',
        ['client_id', 'created_at'],
        unique=False,
        postgresql_where=sa.text('client_id IS NOT NULL AND NOT is_deleted'),
    )
    op.create_index(
        'ix_posts_executor_created',
        'posts',
        ['executor_id', 'created_at'],
        unique=False,
        postgresql_where=sa.text('executor_id IS NOT NULL AND NOT is_deleted'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # Native enum-тип не удаляется вместе с таблицей: без этого повторный
    # upgrade падает с "type post_creator_type already exists".
    op.execute('DROP TYPE IF EXISTS post_creator_type')
    # ### end Alembic commands ###
