"""add car brands for supplier and services as tables

Revision ID: d3cb5b76184e
Revises: e4149105858d
Create Date: 2026-09-07 13:10:50.528931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3cb5b76184e'
down_revision: Union[str, Sequence[str], None] = 'e4149105858d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Тип 'carbrands' уже создан в БД более ранней миграцией (16a808b2ece6) и
# используется колонками services.brands и vehicles.brand. Поэтому здесь
# create_type=False: иначе SQLAlchemy перед созданием таблиц выполнит
# CREATE TYPE carbrands повторно и миграция упадёт с ошибкой
# DuplicateObjectError: type "carbrands" already exists.
CAR_BRANDS: tuple[str, ...] = (
    'all', 'abarth', 'acura', 'aiways', 'alfa_romeo', 'alpine',
    'aston_martin', 'audi', 'baic', 'bentley', 'bestune', 'bmw', 'byd',
    'cadillac', 'changan', 'chery', 'chevrolet', 'chrysler', 'citroen',
    'cupra', 'dacia', 'daewoo', 'daihatsu', 'dodge', 'dongfeng', 'ds',
    'exeed', 'ferrari', 'fiat', 'fisker', 'ford', 'gac', 'geely',
    'genesis', 'gmc', 'great_wall', 'haval', 'honda', 'hongqi', 'hummer',
    'hyundai', 'infiniti', 'isuzu', 'iveco', 'jac', 'jaguar', 'jeep',
    'jetour', 'kia', 'koenigsegg', 'lada', 'lamborghini', 'lancia',
    'land_rover', 'leapmotor', 'lexus', 'lifan', 'lincoln', 'lotus',
    'lucid', 'lynk_and_co', 'maserati', 'maybach', 'mazda', 'mclaren',
    'mercedes', 'mg', 'mini', 'mitsubishi', 'nio', 'nissan', 'opel',
    'pagani', 'peugeot', 'polestar', 'porsche', 'ram', 'renault',
    'rivian', 'rolls_royce', 'rover', 'saab', 'seat', 'skoda', 'smart',
    'ssangyong', 'subaru', 'suzuki', 'tata', 'tesla', 'toyota',
    'vinfast', 'volkswagen', 'volvo', 'voyah', 'xpeng', 'zeekr',
)
carbrands_enum = postgresql.ENUM(*CAR_BRANDS, name='carbrands', create_type=False)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_brands',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('brand', carbrands_enum, nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.executor_id'], ),
    sa.PrimaryKeyConstraint('service_id', 'brand')
    )
    op.create_table('supplier_brands',
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('brand', carbrands_enum, nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.executor_id'], ),
    sa.PrimaryKeyConstraint('supplier_id', 'brand')
    )
    op.drop_column('services', 'brands')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('brands', carbrands_enum, autoincrement=False, nullable=False))
    op.drop_table('supplier_brands')
    op.drop_table('service_brands')
    # ### end Alembic commands ###
