"""add privacy accepted field to client and executor

Revision ID: de45835f6ccf
Revises: 03dd8704ccbd
Create Date: 2026-09-01 09:42:16.810456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de45835f6ccf'
down_revision: Union[str, Sequence[str], None] = '03dd8704ccbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('privacy_accepted', sa.Boolean(), nullable=False))
    op.add_column('executors', sa.Column('privacy_accepted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('executors', 'privacy_accepted')
    op.drop_column('clients', 'privacy_accepted')
    # ### end Alembic commands ###
