"""support request and admin schemas

Revision ID: e4149105858d
Revises: ae6d0a4e1acc
Create Date: 2026-09-06 08:51:45.839350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4149105858d'
down_revision: Union[str, Sequence[str], None] = 'ae6d0a4e1acc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('surname', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('type', sa.Enum('support', 'manager', 'owner', name='admintypes'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_table('support_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('executor_id', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('request_type', sa.Enum('solution', 'error', name='support_request_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('new', 'in_progress', 'needs_info', 'resolved', 'rejected', name='support_request_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('support_comment', sa.Text(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status = 'new' OR admin_id IS NOT NULL", name='ck_support_request_admin_required'),
    sa.CheckConstraint('(client_id IS NULL) <> (executor_id IS NULL)', name='ck_request_one_owner'),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['executor_id'], ['executors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_requests_admin_id'), 'support_requests', ['admin_id'], unique=False)
    op.create_index(op.f('ix_support_requests_client_id'), 'support_requests', ['client_id'], unique=False)
    op.create_index(op.f('ix_support_requests_executor_id'), 'support_requests', ['executor_id'], unique=False)
    op.create_index(op.f('ix_support_requests_request_type'), 'support_requests', ['request_type'], unique=False)
    op.create_index(op.f('ix_support_requests_status'), 'support_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_support_requests_status'), table_name='support_requests')
    op.drop_index(op.f('ix_support_requests_request_type'), table_name='support_requests')
    op.drop_index(op.f('ix_support_requests_executor_id'), table_name='support_requests')
    op.drop_index(op.f('ix_support_requests_client_id'), table_name='support_requests')
    op.drop_index(op.f('ix_support_requests_admin_id'), table_name='support_requests')
    op.drop_table('support_requests')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
